package visualization.controller;

import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.ListView;
import javafx.scene.control.SplitPane;
import javafx.scene.control.Tab;
import javafx.scene.control.TitledPane;
import javafx.scene.layout.VBox;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import visualization.Main;
import visualization.utils.Tools;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.List;

public class OutputController implements Stageable {
    /**
     * The view this controller manages.
     */
    private Stage view;
    /**
     * The container for both the visualisation panels and the formulas panel.
     */
    @FXML
    public SplitPane splitContainer;
    /**
     * ccg2lambda tree representations tab.
     */
    @FXML
    public Tab treeTab;
    /**
     * Box representations container.
     */
    @FXML
    public VBox boxCont;
    /**
     * Graph representations container.
     */
    @FXML
    public VBox graphCont;
    /**
     * ccg2lambda tree representations container.
     */
    @FXML
    private WebView treeCont;
    /**
     * Lambdas/Base Sentences list.
     */
    private List<String[]> lambdaList;

    @FXML
    private ListView<String> lambdaListView;

    private ObservableList<String> lambdaListViewItems = FXCollections.observableArrayList();


    /**
     * Initializes the window, loads the formulas
     */
    @FXML
    public void initialize() {
        getLambdas();
        initVisualisations();
    }

    private void initVisualisations() {
        if (Main.applicationMode == Tools.ApplicationModes.UI)
            displayTreeFromHtml();

        for (String[] s : lambdaList) {
            TitledPane boxPane = initBox(s);
            TitledPane graphPane = initGraph(s);
            boxPane.setExpanded(false);
            graphPane.setExpanded(false);
            boxCont.getChildren().add(boxPane);
            graphCont.getChildren().add(graphPane);
        }
        ((TitledPane) boxCont.getChildren().get(0)).setExpanded(true);
        ((TitledPane) graphCont.getChildren().get(0)).setExpanded(true);
    }

    /**
     * Gets the lambda formulas from the xml file generated by ccg2lambda or given as an argument.
     */
    private void getLambdas() {
        lambdaList = Tools.getSemanticsFormulas(Main.xmlSemanticsFile);
        for (String[] strings : lambdaList) {
            lambdaListViewItems.add(strings[0]);
        }
        lambdaListViewItems.addAll();
        lambdaListView.setItems(lambdaListViewItems);
    }

    /**
     * Initialises the tree display using the html document generated by ccg2lambda.
     */
    public void displayTreeFromHtml() {
        treeTab.setDisable(false);
        final WebEngine webEngine = treeCont.getEngine();
        treeCont.setZoom(2.0);
        webEngine.load(Paths.get("../sentences.html").toUri().toString());

    }

    private TitledPane getLoadedPane(String[] formula, String viewPath) {
        TitledPane loadedPane = null;
        Parametrable<String> stringParametrable;
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource(viewPath));

        try {
            loadedPane = fxmlLoader.load();
            stringParametrable = fxmlLoader.getController();
            stringParametrable.initData(formula);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return loadedPane;
    }

    private TitledPane initGraph(String... formula) {
        TitledPane loadedPane;

        loadedPane = getLoadedPane(formula, "../view/graph.fxml");
        return loadedPane;
    }

    private TitledPane initBox(String... formula) {
        TitledPane loadedPane;

        loadedPane = getLoadedPane(formula, "../view/box.fxml");
        return loadedPane;
    }

    @Override
    public void initStage(Stage primaryStage) {
        this.view = primaryStage;
        ChangeListener<Number> stageSizeListener = (observable, oldValue, newValue) -> {
            Platform.runLater(this::setDividerPosition);
        };
        view.widthProperty().addListener(stageSizeListener);
        view.heightProperty().addListener(stageSizeListener);
    }

    private void setDividerPosition() {
        splitContainer.setDividerPositions(0.8);
    }
}
